//! **本文件由生成器产出,不要手改。**
//!
//! 生成命令:`cargo run --bin gen_translate_tables -- temp/tables src/core/convert/translate/tables_gen.rs`
//! 手工补充放 `mapping.rs`,不受重跑影响。
//!
//! 数据来源:https://creation.bcmcdn.com/neko/web/release/static/js/main-vendors.9b801394.js (sha256 23dd6052f04563c91736e60d929789964b15a48fe330e4ba301135fcd6a4d887)
//! KittenN 版本常量 `bcm_version` = "0.16.2"

/// Kitten → KN 积木类型映射(`LC`,恒等条目也在表里)
pub(super) const KITTEN_TO_KN: &[(&str, &str)] = &[
    (
        "WIDGET_LVMI_bodySensorIs",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "WIDGET_LVMI_bodySensorWhen",
        "bcm_translator_text_event_block",
    ),
    (
        "WIDGET_LVMI_buttonIs",
        "bcm_translator_text_return_boolean_block",
    ),
    ("WIDGET_LVMI_buttonWhen", "bcm_translator_text_event_block"),
    (
        "WIDGET_LVMI_cubeIs",
        "bcm_translator_text_return_boolean_block",
    ),
    ("WIDGET_LVMI_cubeWhen", "bcm_translator_text_event_block"),
    (
        "WIDGET_LVMI_dongJingTieIs",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "WIDGET_LVMI_dongJingTieWhen",
        "bcm_translator_text_event_block",
    ),
    (
        "WIDGET_LVMI_doorWindowSensorIs",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "WIDGET_LVMI_doorWindowSensorWhen",
        "bcm_translator_text_event_block",
    ),
    (
        "WIDGET_LVMI_lightSensorGet",
        "bcm_translator_text_return_value_block",
    ),
    (
        "WIDGET_LVMI_linkageEnable",
        "bcm_translator_text_execution_block",
    ),
    (
        "WIDGET_LVMI_m1sLightSetStatus",
        "bcm_translator_text_execution_block",
    ),
    (
        "WIDGET_LVMI_m1sSetBrightness",
        "bcm_translator_text_execution_block",
    ),
    (
        "WIDGET_LVMI_m1sSetColor",
        "bcm_translator_text_execution_block",
    ),
    (
        "WIDGET_LVMI_sceneRun",
        "bcm_translator_text_execution_block",
    ),
    (
        "WIDGET_LVMI_tempHumiSensorGet",
        "bcm_translator_text_return_value_block",
    ),
    ("add_width_height_scale_2", "add_width_height_scale"),
    ("ai_lab_add_data", "bcm_translator_text_execution_block"),
    ("ai_lab_classify", "bcm_translator_text_return_value_block"),
    (
        "ai_lab_predict_classification",
        "bcm_translator_text_return_value_block",
    ),
    (
        "ai_lab_predict_confidence",
        "bcm_translator_text_return_value_block",
    ),
    ("ask_and_choose", "ask_and_choose"),
    (
        "auto_player_actor_die",
        "bcm_translator_text_execution_block",
    ),
    (
        "auto_player_actor_is_dead",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "auto_player_init_new_model",
        "bcm_translator_text_execution_block",
    ),
    (
        "auto_player_make_decision",
        "bcm_translator_text_execution_block",
    ),
    ("auto_player_on_ai_ready", "bcm_translator_text_event_block"),
    (
        "auto_player_record_features_for_action",
        "bcm_translator_text_execution_block",
    ),
    (
        "auto_player_record_score_and_delete_actor",
        "bcm_translator_text_execution_block",
    ),
    (
        "auto_player_run_game_ai",
        "bcm_translator_text_execution_block",
    ),
    (
        "auto_player_set_action",
        "bcm_translator_text_execution_block",
    ),
    (
        "auto_player_set_feature",
        "bcm_translator_text_execution_block",
    ),
    (
        "auto_player_train_save_restart",
        "bcm_translator_text_execution_block",
    ),
    (
        "auto_player_use_model_supervised",
        "bcm_translator_text_execution_block",
    ),
    (
        "auto_player_use_model_unsupervised",
        "bcm_translator_text_execution_block",
    ),
    ("backdrop_on_change", "bcm_translator_text_event_block"),
    ("break", "break"),
    ("broadcast_input", "broadcast_input"),
    ("bump", "bump_into"),
    ("bump_into_color", "bump_into_color"),
    ("buzzer_play_midi", "bcm_translator_text_execution_block"),
    ("buzzer_sound", "bcm_translator_text_execution_block"),
    ("calculate", "bcm_translator_text_return_value_block"),
    ("capture_or_upload_face_pic", "enable_face_detect_by_photo"),
    ("car_light_on", "bcm_translator_text_execution_block"),
    ("change_cloud_variable", "change_variables"),
    ("change_variable", "change_variables"),
    (
        "change_volume_or_rate_2",
        "bcm_translator_text_execution_block",
    ),
    (
        "check_running_device",
        "bcm_translator_text_return_boolean_block",
    ),
    ("check_screen", "bcm_translator_text_return_boolean_block"),
    ("clear_drawing", "clear_drawing"),
    ("clone", "bcm_translator_text_execution_block"),
    ("cloud_lists_append", "list_append"),
    ("cloud_lists_delete", "delete_list_item"),
    ("cloud_lists_get_value", "list_item"),
    ("cloud_lists_index_of", "list_index_of"),
    ("cloud_lists_insert_value", "list_insert_value"),
    ("cloud_lists_is_exist", "list_is_exist"),
    ("cloud_lists_length", "list_length"),
    ("cloud_lists_replace", "replace_list_item"),
    ("cloud_variables_get", "variables_get"),
    ("cloud_variables_set", "variables_set"),
    (
        "connected_users_get",
        "bcm_translator_text_return_value_block",
    ),
    (
        "continue_pause_video",
        "bcm_translator_text_execution_block",
    ),
    ("controller_shadow", "math_number_with_dial"),
    ("controls_if", "controls_if"),
    ("controls_if_no_else", "controls_if"),
    ("convert_type", "convert_type"),
    ("coordinate_of_sprite", "coordinate_of_sprite"),
    ("create_stage_dialog", "create_stage_dialog"),
    ("dc_both_motor_speed", "bcm_translator_text_execution_block"),
    ("dc_both_motor_turn", "bcm_translator_text_execution_block"),
    (
        "dc_single_motor_speed",
        "bcm_translator_text_execution_block",
    ),
    (
        "dc_single_motor_turn",
        "bcm_translator_text_execution_block",
    ),
    ("default_value", "math_number"),
    (
        "dht11_get_temp_humi",
        "bcm_translator_text_return_value_block",
    ),
    ("digital_show", "bcm_translator_text_execution_block"),
    (
        "display_recognition_result",
        "bcm_translator_text_execution_block",
    ),
    ("dispose", "bcm_translator_text_execution_block"),
    ("dispose_clone", "dispose_clone"),
    ("divisible_by", "divisible_by"),
    (
        "enable_voice_detection",
        "bcm_translator_text_execution_block",
    ),
    ("fan_speed", "bcm_translator_text_execution_block"),
    ("get_3", "appearance_of_sprite"),
    (
        "get_analog_port_value",
        "bcm_translator_text_return_value_block",
    ),
    ("get_answer", "get_answer"),
    ("get_any_midis", "bcm_translator_text_return_value_block"),
    ("get_audios", "get_play_audio"),
    ("get_camera_data", "bcm_translator_text_return_value_block"),
    ("get_choice_or_index", "get_choice_and_index"),
    ("get_clone_index_property", "get_clone_index_property"),
    ("get_clone_num", "get_clone_num"),
    ("get_current_clone_index", "get_current_clone_index"),
    ("get_current_costume", "get_styles"),
    ("get_current_scene", "get_screens"),
    ("get_distance", "bcm_translator_text_return_value_block"),
    ("get_emotion", "check_emotion"),
    ("get_emotion_result", "get_face_detection_result"),
    ("get_face_age", "get_face_detection_result"),
    ("get_face_shape", "check_face_shape"),
    ("get_face_shape_result", "get_face_detection_result"),
    (
        "get_fire_sensor_intensity",
        "bcm_translator_text_return_value_block",
    ),
    ("get_gender", "check_gender"),
    ("get_glasses", "bcm_translator_text_return_boolean_block"),
    (
        "get_light_sensor_intensity",
        "bcm_translator_text_return_value_block",
    ),
    ("get_midis", "bcm_translator_text_return_value_block"),
    (
        "get_mobile_rocker_value",
        "bcm_translator_text_return_value_block",
    ),
    (
        "get_mobile_slope_value",
        "bcm_translator_text_return_value_block",
    ),
    ("get_mouse_info", "get_mouse_info"),
    ("get_notes", "bcm_translator_text_return_value_block"),
    ("get_orientation", "get_orientation"),
    (
        "get_potentiometer_turn_angle",
        "bcm_translator_text_return_value_block",
    ),
    (
        "get_press_intensity",
        "bcm_translator_text_return_value_block",
    ),
    (
        "get_recognition_result",
        "bcm_translator_text_return_value_block",
    ),
    (
        "get_resistance_intensity",
        "bcm_translator_text_return_value_block",
    ),
    (
        "get_running_device",
        "bcm_translator_text_return_value_block",
    ),
    ("get_sensing_current_scene", "get_screens"),
    (
        "get_sound_intensity",
        "bcm_translator_text_return_value_block",
    ),
    ("get_split_options", "text"),
    ("get_stage_info", "get_stage_info"),
    ("get_temp_humi", "bcm_translator_text_return_value_block"),
    ("get_time", "get_time"),
    ("get_voice_answer", "get_voice_answer"),
    ("get_voice_volume", "get_voice_volume"),
    ("get_whole_audios", "get_stop_audio"),
    ("get_whole_midis", "bcm_translator_text_return_value_block"),
    (
        "grayscale_sensor_get",
        "bcm_translator_text_return_value_block",
    ),
    (
        "hcsr04_get_distance",
        "bcm_translator_text_return_value_block",
    ),
    ("hide_ranking", "bcm_translator_text_execution_block"),
    ("image_stamp", "image_stamp"),
    (
        "infrared_sensor_switch",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "is_button_pressed",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "is_color_picked",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "is_digital_port_status",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "is_get_high_temp",
        "bcm_translator_text_return_boolean_block",
    ),
    ("is_get_light", "bcm_translator_text_return_boolean_block"),
    (
        "is_get_magnetic",
        "bcm_translator_text_return_boolean_block",
    ),
    ("is_get_sound", "bcm_translator_text_return_boolean_block"),
    (
        "is_infrared_control",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "is_joystick_pressed",
        "bcm_translator_text_return_value_block",
    ),
    (
        "is_limit_switch_pressed",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "is_ranking_show_hide",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "is_sensor_get_line",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "is_sensor_level",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "is_sensor_touched",
        "bcm_translator_text_return_boolean_block",
    ),
    ("is_switch_on", "bcm_translator_text_return_boolean_block"),
    (
        "is_touch_sensor_switch",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "joystick_get_x_value",
        "bcm_translator_text_return_value_block",
    ),
    (
        "joystick_get_y_value",
        "bcm_translator_text_return_value_block",
    ),
    ("led_light", "bcm_translator_text_execution_block"),
    ("led_light_intensity", "bcm_translator_text_execution_block"),
    ("led_light_on", "bcm_translator_text_execution_block"),
    ("list_get", "list_get"),
    ("lists_append", "list_append"),
    ("lists_copy", "list_copy"),
    ("lists_delete", "delete_list_item"),
    ("lists_get", "pure_list_get"),
    ("lists_get_value", "list_item"),
    ("lists_index_of", "list_index_of"),
    ("lists_insert_value", "list_insert_value"),
    ("lists_is_exist", "list_is_exist"),
    ("lists_length", "list_length"),
    ("lists_replace", "replace_list_item"),
    ("logic_boolean", "logic_boolean"),
    ("logic_compare", "logic_compare"),
    ("logic_negate", "logic_negate"),
    ("logic_operation", "logic_operation"),
    ("math_arithmetic_common", "math_arithmetic"),
    ("math_arithmetic_power", "math_arithmetic"),
    ("math_modulo", "math_modulo"),
    ("math_number_property", "math_number_property"),
    ("math_round", "math_round"),
    ("math_single", "math_function"),
    ("math_trig_arc", "math_trig"),
    ("math_trig_common", "math_trig"),
    (
        "microbit_clear_screen",
        "bcm_translator_text_execution_block",
    ),
    (
        "microbit_display_custom_lattice_image",
        "bcm_translator_text_execution_block",
    ),
    (
        "microbit_display_lattice_image",
        "bcm_translator_text_execution_block",
    ),
    (
        "microbit_display_text",
        "bcm_translator_text_execution_block",
    ),
    (
        "microbit_get_acceleration",
        "bcm_translator_text_return_value_block",
    ),
    (
        "microbit_get_compass_field_strength",
        "bcm_translator_text_return_value_block",
    ),
    (
        "microbit_get_compass_heading",
        "bcm_translator_text_return_value_block",
    ),
    (
        "microbit_get_incline_angle",
        "bcm_translator_text_return_value_block",
    ),
    (
        "microbit_get_light_intensity",
        "bcm_translator_text_return_value_block",
    ),
    (
        "microbit_get_temperature",
        "bcm_translator_text_return_value_block",
    ),
    (
        "microbit_is_incline",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "microbit_is_pin_level",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "microbit_is_press_key",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "microbit_set_light_intensity",
        "bcm_translator_text_execution_block",
    ),
    (
        "microbit_set_xy_light_intensity",
        "bcm_translator_text_execution_block",
    ),
    (
        "microbit_turn_off_xy_light",
        "bcm_translator_text_execution_block",
    ),
    (
        "microbit_when_be_operated",
        "bcm_translator_text_event_block",
    ),
    ("microbit_when_incline", "bcm_translator_text_event_block"),
    ("microbit_when_press_key", "bcm_translator_text_event_block"),
    (
        "midimusic_column_tag",
        "bcm_translator_text_return_value_block",
    ),
    ("mirror", "mirror"),
    ("mobile__set_timer", "set_timer_state"),
    ("mobile__show_timer", "show_hide_timer"),
    ("mobile__timer_value", "timer"),
    ("mobile_change_actor_layer", "set_top_bottom_layer"),
    ("mobile_vibrate", "bcm_translator_text_execution_block"),
    ("mouse_down", "mouse_down"),
    (
        "on_midimusic_play_columns",
        "bcm_translator_text_event_block",
    ),
    ("on_midimusic_play_note", "bcm_translator_text_event_block"),
    ("on_mobile_click_btn", "bcm_translator_text_event_block"),
    ("on_mobile_shake", "bcm_translator_text_event_block"),
    ("on_mobile_slide", "bcm_translator_text_event_block"),
    ("on_mobile_slope", "bcm_translator_text_event_block"),
    ("on_phone_shake", "bcm_translator_text_event_block"),
    ("on_phone_tilt", "bcm_translator_text_event_block"),
    ("on_receive_sound", "bcm_translator_text_event_block"),
    ("on_running_group_activated", "on_running_group_activated"),
    ("on_swipe", "on_swipe"),
    (
        "physics2_allow_rotate",
        "bcm_translator_text_execution_block",
    ),
    (
        "physics2_enable_force",
        "bcm_translator_text_execution_block",
    ),
    (
        "physics2_forbid_bump_with",
        "bcm_translator_text_execution_block",
    ),
    (
        "physics2_get_property",
        "bcm_translator_text_return_value_block",
    ),
    (
        "physics2_set_actor_as",
        "bcm_translator_text_execution_block",
    ),
    (
        "physics2_set_boundary",
        "bcm_translator_text_execution_block",
    ),
    (
        "physics2_set_flexibility",
        "bcm_translator_text_execution_block",
    ),
    ("physics2_set_force", "bcm_translator_text_execution_block"),
    (
        "physics2_set_force_in_time",
        "bcm_translator_text_execution_block",
    ),
    (
        "physics2_set_gravity",
        "bcm_translator_text_execution_block",
    ),
    ("physics2_set_mass", "bcm_translator_text_execution_block"),
    (
        "physics2_set_resilience",
        "bcm_translator_text_execution_block",
    ),
    (
        "physics2_set_roughness",
        "bcm_translator_text_execution_block",
    ),
    ("physics2_set_speed", "bcm_translator_text_execution_block"),
    (
        "physics2_set_texture",
        "bcm_translator_text_execution_block",
    ),
    ("play_ask_record", "bcm_translator_text_execution_block"),
    ("play_audio_2", "play_audio"),
    ("play_audio_and_wait_2", "play_audio_and_wait"),
    ("play_midimusic", "bcm_translator_text_execution_block"),
    (
        "play_midimusic_column",
        "bcm_translator_text_execution_block",
    ),
    (
        "play_midimusic_till_end",
        "bcm_translator_text_execution_block",
    ),
    ("play_video", "bcm_translator_text_execution_block"),
    (
        "play_video_until_end",
        "bcm_translator_text_execution_block",
    ),
    ("play_words_audio", "play_words_audio"),
    ("play_words_audio_wait", "play_word_audio_wait"),
    ("procedures_2_callnoreturn", "procedures_2_callnoreturn"),
    ("procedures_2_callreturn", "procedures_2_callreturn"),
    ("procedures_2_defnoreturn", "procedures_2_defnoreturn"),
    ("procedures_2_parameter", "procedures_2_parameter"),
    ("procedures_2_return_value", "procedures_2_return_value"),
    (
        "procedures_2_stable_parameter",
        "procedures_2_stable_parameter",
    ),
    ("pwm_double_motor", "bcm_translator_text_execution_block"),
    ("random", "random_num"),
    ("repeat_forever", "repeat_forever"),
    ("repeat_forever_until", "repeat_forever_until"),
    ("repeat_n_times", "repeat_n_times"),
    ("restart", "restart"),
    ("rgb_light_color", "bcm_translator_text_execution_block"),
    (
        "rgb_light_color_digital",
        "bcm_translator_text_execution_block",
    ),
    ("self_appear", "self_appear"),
    ("self_ask", "self_ask"),
    ("self_ask_listen", "bcm_translator_text_execution_block"),
    ("self_ask_record", "bcm_translator_text_execution_block"),
    ("self_bounce_off_edge", "self_bounce_off_edge"),
    ("self_broadcast", "self_broadcast"),
    ("self_broadcast_and_wait", "self_broadcast_and_wait"),
    ("self_change_effect_3", "self_change_effect"),
    ("self_change_layer", "bcm_translator_text_execution_block"),
    (
        "self_change_pen_color_property",
        "self_set_pen_color_property",
    ),
    (
        "self_change_pen_color_property_2",
        "self_change_pen_color_property",
    ),
    ("self_change_pen_size", "self_set_pen_size"),
    ("self_change_pen_size_2", "self_change_pen_size"),
    ("self_change_scale_2", "self_change_scale"),
    ("self_clear_effects", "clear_all_effects"),
    ("self_dialog", "self_dialog"),
    ("self_dialog_wait", "self_dialog_wait"),
    ("self_disappear", "self_appear"),
    ("self_distance_to", "distance_to"),
    ("self_face_to", "self_face_to"),
    ("self_face_to_sprite", "self_face_to_sprite"),
    ("self_flip", "bcm_translator_text_execution_block"),
    ("self_glide_to", "self_glide_to"),
    ("self_go_forward", "self_go_forward"),
    ("self_gradually_appear", "self_gradually_appear"),
    ("self_gradually_disappear", "self_gradually_disappear"),
    ("self_gradually_show_hide", "self_gradually_show_hide"),
    ("self_listen", "self_listen"),
    ("self_move_specify", "self_move_specify"),
    ("self_move_specify_sprite", "self_move_specify_sprite"),
    ("self_move_to", "self_move_to"),
    ("self_on_tap", "sprite_on_tap"),
    ("self_out_of_boundary", "out_of_boundary"),
    ("self_pen_down", "self_pen_down"),
    ("self_pen_up", "self_pen_up"),
    ("self_point_towards", "self_point_towards"),
    ("self_prev_next_style", "self_prev_next_style"),
    ("self_rotate", "self_rotate"),
    ("self_rotate_around", "self_rotate_around"),
    ("self_set_draggable", "self_set_draggable"),
    ("self_set_effect", "self_set_effect"),
    ("self_set_effect_2", "self_set_effect"),
    ("self_set_pen_color", "self_set_pen_color"),
    ("self_set_pen_color_property", "self_set_pen_color_property"),
    ("self_set_role_camp", "self_set_role_camp"),
    ("self_set_rotation_type", "self_set_rotation_type"),
    ("self_shake", "bcm_translator_text_execution_block"),
    ("self_translate_animation", "self_stress_animation"),
    (
        "sensor_get_light_intensity",
        "bcm_translator_text_return_value_block",
    ),
    (
        "sensor_get_sound_intensity",
        "bcm_translator_text_return_value_block",
    ),
    ("servo_motor_angle", "bcm_translator_text_execution_block"),
    (
        "set_buzzer_port_value",
        "bcm_translator_text_execution_block",
    ),
    ("set_camera_opcity", "set_camera_alpha"),
    ("set_camera_status", "open_hide_camera"),
    ("set_costume", "set_sprite_style"),
    (
        "set_digital_port_status",
        "bcm_translator_text_execution_block",
    ),
    (
        "set_entity_show_hide",
        "bcm_translator_text_execution_block",
    ),
    ("set_fill_style", "bcm_translator_text_execution_block"),
    ("set_layer_with_pen", "bcm_translator_text_execution_block"),
    (
        "set_midimusic_instrument",
        "bcm_translator_text_execution_block",
    ),
    ("set_midimusic_speed", "bcm_translator_text_execution_block"),
    ("set_pen_path", "bcm_translator_text_execution_block"),
    ("set_pwm_port_value", "bcm_translator_text_execution_block"),
    (
        "set_relay_port_status",
        "bcm_translator_text_execution_block",
    ),
    ("set_scale", "set_scale"),
    ("set_scene_transition", "set_screen_transition"),
    ("set_theatre_layer", "set_top_bottom_layer"),
    (
        "set_volume_or_rate_2",
        "bcm_translator_text_execution_block",
    ),
    ("set_width_height_scale", "set_width_height_scale"),
    ("shadow_number", "shadow_number"),
    ("shadow_text", "text_join"),
    (
        "shake_sensor_intensity",
        "bcm_translator_text_execution_block",
    ),
    ("show_hide_cloud_list", "show_hide_list"),
    ("show_hide_cloud_variable", "show_hide_variables"),
    ("show_hide_list", "show_hide_list"),
    ("show_hide_variable", "show_hide_variables"),
    ("show_hide_video", "bcm_translator_text_execution_block"),
    ("show_ranking", "bcm_translator_text_execution_block"),
    (
        "soil_sensor_get_humi",
        "bcm_translator_text_return_value_block",
    ),
    ("stamp", "stamp"),
    ("start_as_a_mirror", "start_as_a_mirror"),
    ("start_on_click", "on_running_group_activated"),
    ("steering_angle", "bcm_translator_text_execution_block"),
    ("stop", "stop"),
    ("stop_audio_2", "stop_audio"),
    ("stop_midimusic", "bcm_translator_text_execution_block"),
    ("style_of_sprite", "style_of_sprite"),
    ("switch_to_screen", "switch_to_screen"),
    ("sync_tell", "sync_tell"),
    ("tell", "tell"),
    ("terminate", "terminate"),
    ("text_contain", "text_contain"),
    ("text_join", "text_join"),
    ("text_length", "text_length"),
    ("text_select_changeable", "text_select"),
    ("text_split", "text_split"),
    (
        "turn_on_the_qrcode_camera",
        "bcm_translator_text_execution_block",
    ),
    ("user_id_get", "user_id_get"),
    ("username_get", "username_get"),
    ("variables_get", "variables_get"),
    ("variables_set", "variables_set"),
    ("voice_recognition", "voice_recognition"),
    ("wait", "wait"),
    ("wait_until", "wait_until"),
    ("warp", "warp"),
    (
        "weeemake_get_double_line",
        "bcm_translator_text_return_value_block",
    ),
    (
        "weeemake_get_potentiometer_angle",
        "bcm_translator_text_return_value_block",
    ),
    (
        "weeemake_is_get_sport",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "weeemake_joystick_get_x_value",
        "bcm_translator_text_return_value_block",
    ),
    (
        "weeemake_joystick_get_y_value",
        "bcm_translator_text_return_value_block",
    ),
    (
        "weeemake_motor_turn_speed",
        "bcm_translator_text_execution_block",
    ),
    ("when", "when"),
    ("wood_block_get", "bcm_translator_text_return_value_block"),
    ("wood_block_set", "bcm_translator_text_execution_block"),
];

/// 降级占位积木的中文标题(`RC` 的纯字符串部分,按官方原样保留 `{字段}`)
pub(super) const KITTEN_MUTATION_TEXT: &[(&str, &str)] = &[
    ("WIDGET_LVMI_bodySensorIs", "人体传感器检测到{value}经过"),
    ("WIDGET_LVMI_bodySensorWhen", "当人体传感器检测到{value}时"),
    ("WIDGET_LVMI_buttonIs", "无线开关被{value}"),
    ("WIDGET_LVMI_buttonWhen", "当无线开关检测到被{value}时"),
    ("WIDGET_LVMI_cubeIs", "魔方控制器检测到{value}"),
    ("WIDGET_LVMI_cubeWhen", "当魔方控制器检测到{value}"),
    ("WIDGET_LVMI_dongJingTieIs", "动静贴检测到{value}"),
    ("WIDGET_LVMI_dongJingTieWhen", "当动静贴检测到{value}时"),
    ("WIDGET_LVMI_doorWindowSensorIs", "门窗传感器检测到{value}"),
    (
        "WIDGET_LVMI_doorWindowSensorWhen",
        "当门窗传感器检测到{value}时",
    ),
    ("WIDGET_LVMI_lightSensorGet", "光照传感器检测到的光照强度"),
    ("WIDGET_LVMI_linkageEnable", "{value2}{value1}"),
    ("WIDGET_LVMI_m1sLightSetStatus", "M1S网关夜灯{value}"),
    ("WIDGET_LVMI_m1sSetBrightness", "M1S网关夜灯 亮度为{value}"),
    ("WIDGET_LVMI_m1sSetColor", "M1S网关夜灯 颜色为{value}"),
    ("WIDGET_LVMI_sceneRun", "执行{value}"),
    (
        "WIDGET_LVMI_tempHumiSensorGet",
        "温湿度传感器检测到的{value}",
    ),
    (
        "ai_lab_add_data",
        "未命名模型: 添加训练数据 特征1{value} 到{value1}",
    ),
    ("ai_lab_classify", "未命名模型: {value}"),
    (
        "ai_lab_predict_classification",
        "未命名模型: 预测特征1{value}的 分类",
    ),
    (
        "ai_lab_predict_confidence",
        "未命名模型: 预测特征1{value}的 置信度",
    ),
    ("auto_player_actor_die", "AI角色死亡"),
    ("auto_player_actor_is_dead", "AI角色已经死亡"),
    (
        "auto_player_init_new_model",
        "初始化新的模型{value}结构为：输入层{value1}，输出层{value2},，隐藏层{value3}",
    ),
    ("auto_player_make_decision", "AI角色做出决策"),
    ("auto_player_on_ai_ready", "当GameAI启动时"),
    (
        "auto_player_record_features_for_action",
        "为行为不操作记录当前特征值",
    ),
    (
        "auto_player_record_score_and_delete_actor",
        "记录AI角色得分:{value}并删除自己",
    ),
    ("auto_player_run_game_ai", "启动GameAI"),
    ("auto_player_set_action", "AI角色使用行为：{value}{value1}"),
    (
        "auto_player_set_feature",
        "AI角色使用特征：{value}{value1}...",
    ),
    (
        "auto_player_train_save_restart",
        "如果所有AI角色死亡：使用{value}优化模型并保存为{value1}, 重启GameAI",
    ),
    (
        "auto_player_use_model_supervised",
        "设置自己为AI角色，使用模型{value}",
    ),
    (
        "auto_player_use_model_unsupervised",
        "设置自己为AI角色，每轮运行数量{value}，使用以下模型{value1}",
    ),
    ("backdrop_on_change", "当屏幕切换到{value}"),
    ("buzzer_play_midi", "蜂鸣器 播放音调{value}节拍为{value1}拍"),
    ("buzzer_sound", "蜂鸣器{value}{value1}发声"),
    ("calculate", "数学运算 {value}"),
    ("car_light_on", "车尾灯{value}的{value2}"),
    ("clone", "分裂 {sprite_id} 到 x {x} y {y}"),
    ("connected_users_get", "在线用户数"),
    ("dc_both_motor_speed", "双向马达{value}的转动速度{value1}"),
    ("dc_both_motor_turn", "双向马达{value}{value1}转动"),
    ("dc_single_motor_speed", "单向马达{value}转动速度{value1}"),
    ("dc_single_motor_turn", "单向马达{value}{value1}转动"),
    (
        "dht11_get_temp_humi",
        "DHT11温湿度传感器{value}检测到的温度和湿度",
    ),
    ("digital_show", "数码管{value}显示{value}"),
    ("display_recognition_result", "显示二维码的扫描结果"),
    ("dispose", "删除自己"),
    ("fan_speed", "130风扇模块{value}速度为{value1}"),
    ("get_analog_port_value", "模拟接口{value}的值"),
    ("get_distance", "超声波传感器{value}检测到的距离"),
    (
        "get_fire_sensor_intensity",
        "火焰传感器{value}检测到的火焰强度",
    ),
    (
        "get_light_sensor_intensity",
        "光敏传感器{value}检测到的光照强度",
    ),
    ("get_mobile_rocker_value", "{value}摇杆{value1}的值"),
    ("get_mobile_slope_value", "{value}倾斜{value1}分量"),
    ("get_potentiometer_turn_angle", "电位器{value}的旋转量"),
    ("get_press_intensity", "压力传感器{value}检测到的按压强度"),
    ("get_recognition_result", "二维码的扫描结果"),
    ("get_resistance_intensity", "滑动变阻器{value}的移动量"),
    ("get_running_device", "运行设备"),
    ("get_sound_intensity", "声强传感器{value}检测到的声音强度"),
    ("get_temp_humi", "温湿度传感器{value}检测到{value1}"),
    ("grayscale_sensor_get", "灰度传感器{value}检测到的灰度"),
    (
        "hcsr04_get_distance",
        "HCSR04超声波传感器 TRI {value} ECH {value1}检测到的距离",
    ),
    ("hide_ranking", "隐藏 排行榜"),
    ("infrared_sensor_switch", "红外避障传感器{value}检测到障碍"),
    ("is_button_pressed", "按钮被{value}{value1}"),
    (
        "is_color_picked",
        "颜色传感器{value1}{value2}{value3}检测到颜色{value4}",
    ),
    (
        "is_digital_port_status",
        "数字接口{value}的电平状态为{value1}",
    ),
    ("is_get_high_temp", "温度开关 {value} 检测到高温"),
    ("is_get_light", "光敏触控{value}检测到光"),
    ("is_get_magnetic", "磁敏模块 {value} 检测到磁场"),
    ("is_get_sound", "声控{value}检测到声音"),
    ("is_infrared_control", "红外遥控器按下{value}"),
    ("is_joystick_pressed", "摇杆{value}被按下"),
    ("is_limit_switch_pressed", "限位开关被{value}{value1}"),
    ("is_sensor_get_line", "巡线传感器{value}检测到黑线"),
    ("is_sensor_level", "倾斜传感器{value}状态为{value1}"),
    ("is_sensor_touched", "触摸开关被{value}{value1}"),
    ("is_switch_on", "开关被{value}{value1}"),
    ("is_touch_sensor_switch", "触摸传感器{value}被按下"),
    ("joystick_get_x_value", "摇杆{value}上X轴的值"),
    ("joystick_get_y_value", "摇杆{value}上Y轴的值"),
    ("led_light", "LED灯{value}{value1}"),
    ("led_light_intensity", "LED灯{value}亮度为{value1}"),
    ("led_light_on", "LED灯{value}的{value1}"),
    ("microbit_clear_screen", "清空屏幕"),
    (
        "microbit_display_custom_lattice_image",
        "显示自定义图案{value}",
    ),
    ("microbit_display_lattice_image", "显示图案{value}"),
    ("microbit_display_text", "显示文本{value}"),
    ("microbit_get_acceleration", "加速度值{value}"),
    ("microbit_get_compass_field_strength", "指南针磁场值{value}"),
    ("microbit_get_compass_heading", "指南针 角度"),
    ("microbit_get_incline_angle", "向{value}倾斜的角度"),
    ("microbit_get_light_intensity", "亮度级别"),
    ("microbit_get_temperature", "温度"),
    ("microbit_is_incline", "向{value}倾斜"),
    ("microbit_is_pin_level", "引脚{value}的电平状态为{value1}"),
    ("microbit_is_press_key", "按键{value}被按下"),
    ("microbit_set_light_intensity", "设置亮度{value}"),
    (
        "microbit_set_xy_light_intensity",
        "点亮x{value}y{value1}), 亮度为{value2}",
    ),
    ("microbit_turn_off_xy_light", "熄灭x{value}y{value1})"),
    ("microbit_when_be_operated", "当被{value1}"),
    ("microbit_when_incline", "当向{value}倾斜"),
    ("microbit_when_press_key", "当{value}按钮{value1}"),
    ("midi__get_bpm", "MIDI 音乐{midi_get}节拍"),
    (
        "midi__get_playing_column",
        "MIDI 音乐{midi_get}当前播放列数",
    ),
    (
        "midi__get_section_notes",
        "MIDI 音乐{midi_get}第{column}列音符",
    ),
    (
        "midi__on_play_note",
        "当 MIDI 音乐{midi_get}播放音符{midi_get_note}",
    ),
    (
        "midi__on_play_section",
        "每当 MIDI 音乐{midi_get}播放{column}列音符",
    ),
    (
        "midi__play_section",
        "播放 MIDI 音乐{midi_get}第{column}列音符",
    ),
    ("midi__set_program", "设置 MIDI 音乐{midi_get}音色{program}"),
    ("midi__set_speed_rate", "设置 MIDI 音乐播放速率{rate}倍"),
    ("midi_get", "MIDI 音乐"),
    ("midi_get_all", "任意 MIDI 音乐"),
    ("midi_get_note", "音符"),
    ("midimusic_column_tag", "MIDI音乐的第{value}列音符{value}"),
    ("mobile_vibrate", "{value}振动"),
    (
        "on_midimusic_play_columns",
        "每当MIDI音乐{value}播放{value}列音符",
    ),
    (
        "on_midimusic_play_note",
        "当MIDI音乐{value}播放到音符{value1}",
    ),
    ("on_mobile_click_btn", "当{value}上{value1}按下{value2}"),
    ("on_mobile_shake", "当{value}被摇晃"),
    ("on_mobile_slide", "当{value}识别到 手指向{value}滑动"),
    ("on_mobile_slope", "当{value}向倾斜"),
    ("physics2_allow_rotate", "{value}倾倒"),
    ("physics2_enable_force", "{value}外力影响"),
    ("physics2_forbid_bump_with", "与{value}{value1}"),
    ("physics2_get_property", "{value}{value1}"),
    ("physics2_set_actor_as", "{value}物理碰撞"),
    ("physics2_set_boundary", "设置当前屏幕 物理边界为 {value}"),
    ("physics2_set_flexibility", "设置 自身柔软度为{value}"),
    (
        "physics2_set_force",
        "受到 大小{value}方向{value1}度 的推力",
    ),
    (
        "physics2_set_force_in_time",
        "在{value}秒内持续受到 大小{value1}方向{value2}度 的推力",
    ),
    (
        "physics2_set_gravity",
        "设置当前屏幕重力加速度的大小{value}和方向{value1}",
    ),
    ("physics2_set_mass", "设置 自身质量{value}"),
    ("physics2_set_resilience", "设置碰撞时的弹性{value}"),
    ("physics2_set_roughness", "设置摩擦时的粗糙程度{value}"),
    (
        "physics2_set_speed",
        "设置移动速度大小{value}和方向{value1}度",
    ),
    ("physics2_set_texture", "设置 自身材质为{value}"),
    ("play_ask_record", "播放录音"),
    ("play_midimusic", "播放MIDI音乐{value}"),
    (
        "play_midimusic_column",
        "播放MIDI音乐{value}的第{value}列音符",
    ),
    ("play_midimusic_till_end", "播放MIDI音乐{value}直到结束"),
    ("play_video", "播放视频{video}"),
    ("play_video_until_end", "播放视频{video}直到结束"),
    ("program", "音色"),
    (
        "pwm_double_motor",
        "双向马达{value}{value1}转动速度{value2}",
    ),
    (
        "rgb_light_color",
        "RGB超声波传感器{value}上{value1}灯颜色为{value2}",
    ),
    (
        "rgb_light_color_digital",
        "RGB超声波传感器{value}上{value1}灯颜色为：R{value2}G{value3}B{value4}",
    ),
    ("self_ask_record", "询问 {text} 并录音"),
    ("self_change_layer", "将图层上移到 {layer} 层"),
    ("self_shake", "抖动{value} 秒"),
    ("sensor_get_light_intensity", "光线传感器 检测到的光照强度"),
    ("sensor_get_sound_intensity", "声音传感器 检测到的声音强度"),
    ("servo_motor_angle", "舵机{value}的角度{value1}"),
    ("set_buzzer_port_value", "设置蜂鸣器接口{value}的值{value1}"),
    ("set_camera_opcity", "设置视频透明度{value}"),
    (
        "set_digital_port_status",
        "设置数字接口{value}的电平状态{value1}",
    ),
    ("set_fill_style", "设置填充颜色"),
    (
        "set_midimusic_instrument",
        "设置MIDI音乐{value}的乐器为{value}",
    ),
    ("set_midimusic_speed", "设置MIDI音乐播放速率为{value}"),
    ("set_pwm_port_value", "设置PWM接口{value}值为{value1}"),
    (
        "set_relay_port_status",
        "设置继电器接口{value}的电平状态为{value1}",
    ),
    (
        "shake_sensor_intensity",
        "振动模块{value}的振动强度{value1}",
    ),
    ("show_ranking", "显示{value}排行榜"),
    ("soil_sensor_get_humi", "土壤湿度传感器{value}检测到的湿度"),
    ("steering_angle", "9g舵机{value}角度为{value1}"),
    ("stop_midimusic", "停止{value}MIDI音乐"),
    ("turn_on_the_qrcode_camera", "开启设备的摄像头，扫描二维码"),
    ("user_id_get", "用户ID"),
    ("username_get", "用户名"),
    (
        "weeemake_get_double_line",
        "双路巡线传感器{value}{value1}检测到的灰度",
    ),
    ("weeemake_get_potentiometer_angle", "电位器{value}的旋转量"),
    ("weeemake_is_get_sport", "人体红外传感器{value}检测到运动"),
    ("weeemake_joystick_get_x_value", "摇杆{value}上X轴的值"),
    ("weeemake_joystick_get_y_value", "摇杆{value}上Y轴的值"),
    (
        "weeemake_motor_turn_speed",
        "电机马达{value}的转动速度为{value1}",
    ),
    ("wood_block_get", "海龟函数{value}"),
    ("wood_block_set", "海龟函数{value}"),
];

/// `RC` 里由官方 handler 按字段选词的部分(我们按选择器近似,见 docs/rounds/20 已知偏差)
pub(super) const KITTEN_MUTATION_TEXT_SELECT: &[(&str, &[(&str, &str)])] = &[
    (
        "change_volume_or_rate_2",
        &[
            ("decrease", "减少"),
            ("increase", "增加"),
            ("rate", "音速"),
            ("volume", "音量"),
        ],
    ),
    (
        "check_running_device",
        &[
            ("computer", "运行设备为电脑"),
            ("mobile", "运行设备为手机"),
            ("tablet", "运行设备为平板电脑"),
        ],
    ),
    (
        "check_screen",
        &[("false", "离开屏幕 {index}"), ("true", "留在屏幕 {index}")],
    ),
    (
        "continue_pause_video",
        &[
            ("continue", "继续视频{video}"),
            ("pause", "暂停视频{video}"),
        ],
    ),
    (
        "enable_voice_detection",
        &[("close", "关闭声音侦测"), ("open", "开启声音侦测")],
    ),
    (
        "get_camera_data",
        &[
            ("direction", "{entity_id}的运动方向"),
            ("motion", "{entity_id}的运动强度"),
        ],
    ),
    (
        "get_glasses",
        &[
            ("common", "眼镜佩戴为普通眼镜"),
            ("none", "眼镜佩戴为无眼镜"),
            ("sun", "眼镜佩戴为墨镜"),
        ],
    ),
    (
        "is_ranking_show_hide",
        &[("hide", "排行榜隐藏"), ("show", "排行榜显示")],
    ),
    ("logic_boolean", &[("FALSE", "不成立"), ("TRUE", "成立")]),
    (
        "self_ask_listen",
        &[
            ("en", "询问{text}并识别为英文"),
            ("zh-hans", "询问{text}并识别为中文"),
        ],
    ),
    ("self_flip", &[("0", "上下翻转"), ("1", "左右翻转")]),
    (
        "set_camera_status",
        &[("false", "关闭摄像头"), ("true", "打开摄像头")],
    ),
    (
        "set_entity_show_hide",
        &[
            ("grad_hide", "逐渐隐藏"),
            ("grad_show", "逐渐显示"),
            ("hide", "隐藏"),
            ("show", "显示"),
        ],
    ),
    (
        "set_layer_with_pen",
        &[
            ("above", "将角色移至画笔图层上方"),
            ("below", "将角色移至画笔图层下方"),
        ],
    ),
    (
        "set_pen_path",
        &[
            ("end_point", "设置当前为填充终点"),
            ("start_point", "设置当前为填充起点"),
        ],
    ),
    (
        "set_volume_or_rate_2",
        &[("rate", "音速"), ("volume", "音量")],
    ),
    (
        "show_hide_video",
        &[("hide", "隐藏视频{video}"), ("show", "显示视频{video}")],
    ),
];

/// 每个块的默认 shadow XML 覆盖表(`cy`)
pub(super) const SHADOW_XML: &[(&str, &[(&str, &str)])] = &[
    (
        "ai_chat_ask",
        &[(
            "text",
            "<shadow type=\"limit_length_text\" visible=\"visible\"><field name=\"TEXT\">你好</field></shadow>",
        )],
    ),
    (
        "procedures_2_return_value",
        &[("VALUE", "<shadow type=\"procedure_boolean\"/>")],
    ),
    (
        "self_point_towards",
        &[(
            "degrees",
            "<shadow type=\"math_number_with_dial\" visible=\"visible\"><field constraints=\"-180,180,0,true\" name=\"NUM\">90</field></shadow>",
        )],
    ),
    (
        "self_set_pen_size",
        &[(
            "size",
            "<shadow type=\"color_size_slider\" visible=\"visible\"><field constraints=\"1,1000,0,\" name=\"NUM\">10</field></shadow>",
        )],
    ),
    (
        "set_camera_alpha",
        &[(
            "camera_alpha",
            "<shadow type=\"camera_alpha_slider\" visible=\"visible\"><field constraints=\"0,100,0,false\" name=\"NUM\">60</field></shadow>",
        )],
    ),
    (
        "set_system_preset",
        &[(
            "text",
            "<shadow type=\"multiline_text\" visible=\"visible\"><field name=\"TEXT\">你是一个AI助手</field></shadow>",
        )],
    ),
    (
        "set_webcam_alpha",
        &[(
            "camera_alpha",
            "<shadow type=\"camera_alpha_slider\" visible=\"visible\"><field constraints=\"0,100,0,false\" name=\"NUM\">60</field></shadow>",
        )],
    ),
];

/// 中文名反查(类型 → 中文 token),占位积木标题兜底
pub(super) const ZH_NAME_BY_TYPE: &[(&str, &str)] = &[
    ("add_width_height_scale", "改变角色宽高"),
    ("ai_chat_answer", "AI对话_获得AI回答"),
    ("ai_chat_ask", "AI对话_向AI询问"),
    ("ai_text_actor", "文本识别_识别角色文本"),
    ("ai_text_photo", "文本识别_拍照识别文本"),
    ("ai_text_result", "文本识别_文本识别结果"),
    ("ai_text_result_check", "文本识别_识别结果包含"),
    ("appearance_of_sprite", "角色属性值"),
    ("ask_and_choose", "弹出选择框"),
    (
        "bcm_translator_text_event_block",
        "bcm_translator_text_event_block",
    ),
    (
        "bcm_translator_text_execution_block",
        "bcm_translator_text_execution_block",
    ),
    (
        "bcm_translator_text_return_boolean_block",
        "bcm_translator_text_return_boolean_block",
    ),
    (
        "bcm_translator_text_return_value_block",
        "bcm_translator_text_return_value_block",
    ),
    ("break", "退出循环"),
    ("bump_into", "判断角色碰撞"),
    ("bump_into_body_part", "摄像_碰到面部"),
    ("bump_into_color", "判断颜色碰撞"),
    ("change_variables", "改变变量"),
    ("check_emotion", "认知AI_情绪为高兴"),
    ("check_face_shape", "认知AI_脸型为方脸"),
    ("check_gender", "认知AI_性别为男生"),
    ("check_key", "侦测键盘值"),
    ("check_tilt_direction_of_face", "摄像_面部向左倾斜"),
    ("clear_all_effects", "清除特效"),
    ("clear_drawing", "清除画笔"),
    ("close_self_dialog", "关闭提示"),
    ("console_log", "打印"),
    ("controls_if", "如果"),
    ("convert_type", "类型转换"),
    ("coordinate_of_sprite", "角色坐标"),
    ("create_stage_dialog", "弹出对话框"),
    ("delete_list_item", "删除列表项"),
    ("dispose_clone", "删除本克隆体"),
    ("distance_to", "到对象的距离"),
    ("divisible_by", "整除判断"),
    ("effect_of_sprite", "角色特效值"),
    ("enable_face_detect_by_actor", "认知AI_识别角色面部"),
    ("enable_face_detect_by_photo", "认知AI_拍照识别面部"),
    ("enable_object_detect_by_actor", "认知AI_识别角色物体类别"),
    ("enable_object_detect_by_photo", "认知AI_拍照识别物体类别"),
    ("evaluate_actor_style", "分类AI_识别角色造型分类"),
    ("evaluate_camera", "分类AI_识别摄像画面分类"),
    ("evaluate_photo", "分类AI_拍照并识别分类"),
    ("face_to_body_part", "摄像_面向面部"),
    ("get_answer", "输入框结果"),
    ("get_appearance_of_part", "摄像_面部的大小宽高"),
    ("get_choice_and_index", "选择框结果"),
    ("get_clone_index_property", "克隆体属性"),
    ("get_clone_num", "克隆体总数"),
    ("get_current_clone_index", "克隆体编号"),
    ("get_evaluate_class_accuracy", "分类AI_分类置信度"),
    ("get_evaluate_class_name", "分类AI_分类结果"),
    ("get_face_detection_result", "认知AI_面部识别结果"),
    ("get_mouse_info", "鼠标坐标"),
    ("get_object_detection_result", "认知AI_物体识别结果"),
    ("get_orientation", "手机倾斜值"),
    ("get_position_of_body_part", "摄像_面部的坐标"),
    ("get_stage_info", "舞台属性"),
    ("get_tilt_angle_of_face", "摄像_面部的倾斜角度"),
    ("get_time", "当前时间"),
    ("get_voice_answer", "语音识别结果"),
    ("get_voice_volume", "麦克风音量"),
    ("global_animation", "设置全局特效"),
    ("image_stamp", "设置图像印章"),
    ("list_append", "添加列表项"),
    ("list_copy", "复制列表项"),
    ("list_get", "获取列表项"),
    ("list_index_of", "查找列表值首次位置"),
    ("list_insert_value", "插入列表项"),
    ("list_is_exist", "判断列表值是否存在"),
    ("list_item", "列表值"),
    ("list_length", "列表长度"),
    ("logic_boolean", "逻辑值"),
    ("logic_compare", "两值比较"),
    ("logic_negate", "取反"),
    ("logic_operation", "逻辑运算"),
    ("math_arc_trig", "math_arc_trig"),
    ("math_arithmetic", "两值计算"),
    ("math_arithmetic_power", "math_arithmetic_power"),
    ("math_function", "科学计算"),
    ("math_modulo", "余数运算"),
    ("math_number_property", "数值判断"),
    ("math_round", "舍入运算"),
    ("math_trig", "三角函数"),
    ("mirror", "克隆"),
    ("mouse_down", "侦测触发值"),
    ("move_to_body_part", "摄像_移到面部"),
    ("new_conversation", "AI对话_开启新对话"),
    ("on_bump_actor", "当碰撞发生"),
    ("on_bump_actor_value", "角色属性"),
    ("on_keydown", "当键盘触发"),
    ("on_running_group_activated", "当开始运行"),
    ("on_swipe", "当滑动屏幕"),
    ("open_close_webcam", "分类AI_开启摄像头"),
    ("open_hide_camera", "摄像_开启摄像头"),
    ("out_of_boundary", "判断离开边缘"),
    ("play_audio", "播放声音"),
    ("play_audio_and_wait", "播放声音直到结束"),
    ("play_word_audio_wait", "播放文本直到结束"),
    ("play_words_audio", "播放文本"),
    ("procedures_2_actor_param", "函数角色"),
    ("procedures_2_return_value", "函数返回"),
    ("random_num", "随机整数"),
    ("received_broadcast", "判断是否收到广播"),
    ("recognize_body_part", "摄像_识别到面部"),
    ("recognize_gesture", "摄像_手势为剪刀"),
    ("repeat_forever", "永远循环"),
    ("repeat_forever_until", "重复直到"),
    ("repeat_n_times", "重复循环"),
    ("replace_list_item", "替换列表项"),
    ("restart", "重启"),
    ("script_variables", "定义脚本变量"),
    ("self_appear", "设置角色状态"),
    ("self_appear_animation", "设置入场特效"),
    ("self_ask", "弹出输入框"),
    ("self_bounce_off_edge", "设置碰到边缘反弹"),
    ("self_broadcast", "发送广播"),
    ("self_broadcast_and_wait", "发送广播并等待"),
    ("self_broadcast_with_param", "发送广播带参数"),
    ("self_change_coordinate", "self_change_coordinate"),
    ("self_change_coordinate_x", "改变x坐标"),
    ("self_change_coordinate_y", "改变y坐标"),
    ("self_change_effect", "改变特效"),
    ("self_change_pen_color_property", "改变画笔特效"),
    ("self_change_pen_size", "改变画笔粗细"),
    ("self_change_scale", "改变角色大小"),
    ("self_dialog", "弹出提示指定秒数"),
    ("self_dialog_wait", "弹出提示"),
    ("self_face_to", "面向对象"),
    ("self_face_to_sprite", "设置面向对象"),
    ("self_glide_coordinate", "self_glide_coordinate"),
    ("self_glide_coordinate_x", "逐渐改变x坐标"),
    ("self_glide_coordinate_y", "逐渐改变y坐标"),
    ("self_glide_to", "逐渐移动"),
    ("self_go_forward", "移动步数"),
    ("self_gradually_show_hide", "逐渐改变角色状态"),
    ("self_listen", "当收到广播"),
    ("self_listen_with_param", "当收到广播带参数"),
    ("self_move_specify", "移到"),
    ("self_move_specify_sprite", "移动到"),
    ("self_move_to", "移到位置"),
    ("self_pen_down", "落笔"),
    ("self_pen_up", "抬笔"),
    ("self_point_towards", "设置面向角度"),
    ("self_prev_next_style", "切换造型"),
    ("self_rotate", "旋转角度"),
    ("self_rotate_around", "围绕角色旋转"),
    ("self_set_draggable", "设置角色拖动"),
    ("self_set_effect", "设置特效"),
    ("self_set_pen_color", "设置画笔颜色"),
    ("self_set_pen_color_property", "设置画笔特效"),
    ("self_set_pen_size", "设置画笔粗细"),
    ("self_set_position", "self_set_position"),
    ("self_set_position_x", "设置x坐标"),
    ("self_set_position_y", "设置y坐标"),
    ("self_set_role_camp", "设置角色阵营"),
    ("self_set_rotation_type", "设置旋转模式"),
    ("self_stress_animation", "设置强调特效"),
    ("self_text_effect_color", "设置文字颜色"),
    ("self_text_effect_size", "设置文字字号"),
    ("self_text_effect_text", "将角色变为文字"),
    ("send_judge_result", "通知判题结果"),
    ("set_camera_alpha", "摄像_设置不透明度"),
    ("set_pen_layer", "移动画笔图层"),
    ("set_scale", "设置角色大小"),
    ("set_screen_transition", "设置切屏特效"),
    ("set_sprite_style", "设置造型"),
    ("set_system_preset", "AI对话_设置系统提示词"),
    ("set_timer_state", "执行计时器"),
    ("set_top_bottom_layer", "移动角色图层"),
    ("set_webcam_alpha", "分类AI_设置摄像头不透明度"),
    ("set_width_height_scale", "设置角色宽高"),
    ("shadow_text", "shadow_text"),
    ("show_hide_list", "设置列表状态"),
    ("show_hide_ranking", "设置排行榜状态"),
    ("show_hide_timer", "设置计时器状态"),
    ("show_hide_variables", "设置变量状态"),
    ("sound_color", "设置说话音色为"),
    ("sprite_on_tap", "当触发事件"),
    ("stamp", "设置文字印章"),
    ("start_as_a_mirror", "当克隆体启动"),
    ("stop", "停止脚本"),
    ("stop_audio", "停止声音"),
    ("style_of_sprite", "造型编号"),
    ("switch_to_screen", "切换到屏幕"),
    ("sync_tell", "告诉执行并等待"),
    ("tell", "告诉执行"),
    ("temporary_list", "临时列表"),
    ("text_contain", "字符串包含判断"),
    ("text_join", "连接字符串"),
    ("text_length", "字符串长度"),
    ("text_select", "选择字符串"),
    ("text_split", "分开字符串"),
    ("timer", "计时器值"),
    ("translate", "弹出翻译弹窗"),
    ("translate_result", "翻译结果"),
    ("traverse_number", "遍历循环"),
    ("update_ranking", "更新排行榜"),
    ("user_id_get", "当前用户ID"),
    ("user_info_of_th", "排行榜具体名次的用户信息"),
    ("user_ranking_info", "当前用户排行榜信息"),
    ("username_get", "当前用户名"),
    ("variables_set", "设置变量"),
    ("voice_recognition", "弹出语音识别弹窗"),
    ("wait", "等待秒数"),
    ("wait_until", "等待直到"),
    ("warp", "一步执行"),
    ("when", "当条件满足时触发"),
];

/// KN 里的四种「文本占位积木」
pub(super) const TEXT_PLACEHOLDER_BLOCKS: [&str; 4] = [
    "bcm_translator_text_execution_block",
    "bcm_translator_text_event_block",
    "bcm_translator_text_return_value_block",
    "bcm_translator_text_return_boolean_block",
];

/// 目标格式版本常量(`qC.bcm_version`)
///
/// 可见性是 `core::convert`:域级工具 `upload.rs` 的 `bcm_version` 兜底要读它
/// (`upload.rs` 在 `translate` 之外,`pub(super)` 不够,`pub(crate)` 又过宽)。
pub(in crate::core::convert) const BCM_VERSION: &str = "0.16.2";
/// 竖屏画布(562×900)
pub(super) const STAGE_PORTRAIT: (f64, f64) = (562.0, 900.0);
/// 横屏画布(900×562)
pub(super) const STAGE_LANDSCAPE: (f64, f64) = (900.0, 562.0);
